name: task_manager
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^1.0.3
  flutter_svg: ^1.0.3
  objectbox: ^1.3.0
  objectbox_flutter_libs: ^1.3.0
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  flutter_lints: ^1.0.4
  objectbox_generator: ^1.3.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/svg/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-Bold.ttf
        - asset: assets/fonts/nunito/Nunito-ExtraBold.ttf
        - asset: assets/fonts/nunito/Nunito-Medium.ttf
        - asset: assets/fonts/nunito/Nunito-Regular.ttf
        - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
          weight: 700
